const data = [
  {
    id: 1,
    image: "/images/HTML.png",
    title: "HTML Tutorial",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    category: "frontend",
  },
  {
    id: 2,
    image: "/images/css.png",
    title: "CSS Tutorial",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    category: "frontend",
  },
  {
    id: 3,
    image: "/images/JS.png",
    title: "JS Tutorial",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    category: "frontend",
  },
  {
    id: 4,
    image: "/images/react.png",
    title: "React Js Tutorial",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    category: "frontend",
  },
  {
    id: 5,
    image: "/images/bootsrap.png",
    title: "Bootstrap Tutorial",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    category: "frontend",
  },
  {
    id: 6,
    image: "/images/php.png",
    title: "PHP Tutorial",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    category: "backend",
  },
  {
    id: 7,
    image: "/images/node.png",
    title: "Node.js Tutorial",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    category: "backend",
  },
  {
    id: 8,
    image: "/images/ASAP.jpeg",
    title: "ASP Tutorial",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    category: "backend",
  },
  {
    id: 9,
    image: "/images/SQL.png",
    title: "SQL Tutorial",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    category: "database",
  },
  {
    id: 10,
    image: "/images/mongoDB.jpeg",
    title: "Mongo DB Tutorial",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    category: "database",
  },
  {
    id: 11,
    image: "/images/C.jpeg",
    title: "C Tutorial",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    category: "programming",
  },
  {
    id: 12,
    image: "/images/C++.png",
    title: "C++ Tutorial",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    category: "programming",
  },
  {
    id: 13,
    image: "/images/java.png",
    title: "Java Tutorial",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    category: "programming",
  },
  {
    id: 14,
    image: "/images/python.jpeg",
    title: "Python Tutorial",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    category: "programming",
  },
  {
    id: 15,
    image: "/images/Go.png",
    title: "Go Tutorial",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    category: "programming",
  },
];

export default data;
